name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.221.39.118
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /usr/share/nginx/html
            git pull
